---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets
  namespace: vss
spec:
  hostAPI: https://secret.pyler.ai/api
  resyncInterval: 300
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: data-center-r-ao-c
        envSlug: sel1
        secretsPath: "/vss"
        recursive: true
      credentialsRef:
        secretName: infisical-secrets
        secretNamespace: infisical
  managedSecretReference:
    secretName: infisical-managed-secrets
    secretNamespace: vss
    creationPolicy: "Orphan"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ngc-docker-reg-secret
  namespace: vss
spec:
  hostAPI: https://secret.pyler.ai/api
  resyncInterval: 300
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-secrets
        secretNamespace: infisical
      secretsScope:
        projectSlug: data-center-r-ao-c
        envSlug: sel1
        secretsPath: "/vss/docker"
        recursive: false
  managedSecretReference:
    secretName: ngc-docker-reg-secret
    secretNamespace: vss
    creationPolicy: Orphan
    secretType: kubernetes.io/dockerconfigjson