apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vss-web-240
  namespace: vss-240
spec:
  ingressClassName: cilium
  rules:
  - host: vss-web-240.idc.local
    http:
      paths:
      - backend:
          service:
            name: vss-service
            port:
              number: 9000
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vss-api-240
  namespace: vss-240
spec:
  ingressClassName: cilium
  rules:
  - host: vss-api-240.idc.local
    http:
      paths:
      - backend:
          service:
            name: vss-service
            port:
              number: 8000
        path: /
        pathType: Prefix