apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vss-base.fullname" . }}-secrets
  labels:
    {{- include "vss-base.labels" . | nindent 4 }}
type: Opaque
stringData:
  ngc-api-key: {{ .Values.global.ngcApiKey | quote }}
  {{- if .Values.global.nvidiaApiKey }}
  nvidia-api-key: {{ .Values.global.nvidiaApiKey | quote }}
  {{- end }}
---
{{- if .Values.global.ngcApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: nvcr-secret
  labels:
    {{- include "vss-base.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"nvcr.io":{"username":"$oauthtoken","password":"%s"}}}` .Values.global.ngcApiKey | b64enc | quote }}
{{- end }}
