apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-server
  namespace: vss
  labels:
    app: qwen-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-server
  template:
    metadata:
      labels:
        app: qwen-server
    spec:
      # 보안 설정
      securityContext:
        fsGroup: 1000
      containers:
      - name: qwen-server
        image: harbor.pyler.local/apps/qwen-server:IMAGE_TAG
        command: ["/bin/bash"]
        args: ["/app/start.sh"]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: qwen-model-config
        env:
        - name: NVIDIA_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: infisical-managed-secrets

        resources:
          requests:
            nvidia.com/gpu: "2"
          limits:
            nvidia.com/gpu: "2"

        volumeMounts:
        - mountPath: /tmp/via-ngc-model-cache
          name: ngc-model-cache-volume
        - mountPath: /dev/shm
          name: shm-volume
      volumes:
      - name: ngc-model-cache-volume
        persistentVolumeClaim:
          claimName: qwen-ngc-model-cache-pvc
      - emptyDir:
          medium: Memory
          sizeLimit: 16Gi
        name: shm-volume
      schedulerName: bin-packing-scheduler
      nodeSelector:
        pyler.io/group: dgx