apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-ngc-model-cache-pvc
  namespace: vss
  labels:
    app: qwen-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gpfs