# Sample prompt for testing VILA server with logging
import requests
import base64
from PIL import Image
import io

# Create a test image or use a real one
def create_test_image():
    img = Image.new('RGB', (224, 224), color='blue')
    buffer = io.BytesIO()
    img.save(buffer, format='JPEG')
    img_data = buffer.getvalue()
    return base64.b64encode(img_data).decode('utf-8')

# Test prompt matching CompOpenAIModel format
test_prompt = {
    "model": "vila-1.5",
    "messages": [
        {
            "role": "system",
            "content": [
                {
                    "type": "text", 
                    "text": "These are images sampled from a video at timestamps in seconds : <10.5> <15.2> <20.8> .Make sure the answer contain correct timestamps."
                }
            ]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:image/jpeg;base64,{create_test_image()}",
                        "detail": "auto"
                    }
                },
                {
                    "type": "text",
                    "text": "What do you see in this image? Please mention the timestamps."
                }
            ]
        }
    ],
    "max_tokens": 150,
    "temperature": 0.2
}

print("Sending request to VILA server...")
print(f"Request ID will be generated by server")
print(f"Check logs in the 'logs/' directory for detailed flow")

# Send to your VILA server
response = requests.post(
    "http://0.0.0.0:8001/v1/chat/completions",
    json=test_prompt,
    headers={"Content-Type": "application/json"}
)

print("\n" + "="*50)
print("RESPONSE:")
print("="*50)
print(response.json())