services:
  replaystream-ms-1-smc:
    image: ${VST_REPLAYSTREAM_IMAGE}
    profiles: ["bp_smc_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    user: "0:0"
    runtime: nvidia
    container_name: replaystream-ms-1-smc
    network_mode: host
    entrypoint: ["/bin/bash", "-c", "if [ \"$$VST_INSTALL_ADDITIONAL_PACKAGES\" = \"true\" ]; then /home/vst/vst_release/tools/user_additional_install.sh; fi && exec /home/vst/vst_release/launch_vst"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VST_INSTALL_ADDITIONAL_PACKAGES=${VST_INSTALL_ADDITIONAL_PACKAGES}
      - ADAPTOR=replaystream-ms
      - HTTP_PORT=${REPLAYSTREAM_HTTP_PORT_1}
      - CENTRALIZE_DB_NAME=${CENTRALIZE_DB_NAME}
      - CENTRALIZE_DB_USERNAME=${CENTRALIZE_DB_USERNAME}
      - STORAGE_MODULE_ENDPOINT=${STORAGE_MODULE_ENDPOINT}
      - VST_INGRESS_ENDPOINT=${VST_INGRESS_ENDPOINT}
    volumes:
      - ${VST_CONFIG_PATH}:/home/vst/vst_release/configs
      - ${VST_CONFIG_PATH}/vst_config_${STREAM_TYPE:-redis}.json:/home/vst/vst_release/configs/vst_config.json
      - ${VST_DATA_PATH}:/home/vst/vst_release/vst_data
      - ${VST_VIDEO_STORAGE_PATH}:/home/vst/vst_release/vst_video
      - ${CLIP_STORAGE_PATH}:/home/vst/vst_release/streamer_videos
      - ${VST_TEMP_FILES_PATH}:/home/vst/vst_release/webroot/temp_files
      - ${MDX_SAMPLE_APPS_DIR}/vst/scripts/user_additional_install.sh:/home/vst/vst_release/tools/user_additional_install.sh
    deploy:
      restart_policy:
        condition: always
    depends_on:
      centralizedb-smc:
        condition: service_started
      vst-ingress-smc:
        condition: service_started
      storage-ms-smc:
        condition: service_started

#Uncomment this to scale upto 2 replaystream-ms
  # replaystream-ms-2:
  #   image: ${VST_REPLAYSTREAM_IMAGE}
  #   user: "0:0"
  #   runtime: nvidia
  #   container_name: replaystream-ms-2
  #   network_mode: host
  #   entrypoint: ["/bin/bash", "-c", "if [ \"$$VST_INSTALL_ADDITIONAL_PACKAGES\" = \"true\" ]; then /home/vst/vst_release/tools/user_additional_install.sh; fi && exec /home/vst/vst_release/launch_vst"]
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - VST_INSTALL_ADDITIONAL_PACKAGES=${VST_INSTALL_ADDITIONAL_PACKAGES}
  #     - ADAPTOR=replaystream-ms
  #     - HTTP_PORT=${REPLAYSTREAM_HTTP_PORT_2}
  #     - CENTRALIZE_DB_NAME=${CENTRALIZE_DB_NAME}
  #     - CENTRALIZE_DB_USERNAME=${CENTRALIZE_DB_USERNAME}
  #     - STORAGE_MODULE_ENDPOINT=${STORAGE_MODULE_ENDPOINT}
  #   volumes:
  #     - ${VST_CONFIG_PATH}:/home/vst/vst_release/configs
  #     - ${VST_CONFIG_PATH}/vst_config_${STREAM_TYPE:-redis}.json:/home/vst/vst_release/configs/vst_config.json
  #     - ${VST_DATA_PATH}:/home/vst/vst_release/vst_data
  #     - ${VST_VIDEO_STORAGE_PATH}:/home/vst/vst_release/vst_video
  #     - ${CLIP_STORAGE_PATH}:/home/vst/vst_release/streamer_videos
  #     - ${VST_TEMP_FILES_PATH}:/home/vst/vst_release/webroot/temp_files
  #   deploy:
  #     restart_policy:
  #       condition: always
  #   depends_on:
  #     centralizedb:
  #       condition: service_started
  #     vst-ingress:
  #       condition: service_started
  #     storage-ms:
  #       condition: service_started

  sdr-http-replaystream-smc:
    image: ${SDR_IMAGE}
    profiles: ["bp_smc_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    user: "0:0"
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "8192m"
        max-file: "3"
    container_name: sdr-http-replaystream-smc
    volumes:
      - ./sdr-config:/wdm-configs
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VST_DATA_PATH}/sdr/replaystream/log:/log
    environment:
      PORT: 4004
      WDM_CLUSTER_CONFIG_FILE: /wdm-configs/docker_cluster_config.json
      WDM_MSG_KEY: ${REDIS_MSG_KEY}
      WDM_WL_REDIS_SERVER: ${REDIS_HOSTADDR}
      WDM_WL_REDIS_PORT: ${REDIS_PORT}
      WDM_WL_REDIS_MSG_FIELD: sensor.id
      WDM_WL_ADD_URL: /api/v1/replay/stream/add
      WDM_WL_DELETE_URL: /api/v1/replay/stream/
      WDM_WL_HEALTH_CHECK_URL: /api/v1/replay/configuration
      WDM_WL_CHANGE_ID_ADD: camera_streaming
      WDM_WL_CHANGE_ID_DEL: camera_remove
      WDM_PRELOAD_WORKLOAD: ./tests/event_pre-roll.json
      WDM_CLEAR_DATA_WL: true
      WDM_KFK_ENABLE: false
      WDM_MSG_TOPIC: vst_events
      WDM_KFK_BOOTSTRAP_URL: ${KAFKA_BOOTSTRAP_URL}
      WDM_DS_SWAP_ID_NAME: false
      WDM_WL_THRESHOLD: 500
      WDM_ADD_REMOVE_RETRY_ATTEMPTS: 50
      WDM_CLUSTER_TYPE: docker
      WDM_POD_WATCH_DOCKER_DELAY: 0.5
      WDM_RESTART_DS_ON_ADD_FAIL: false
      WDM_DISABLE_WERKZEUG_LOGGING: true
      WDM_WL_OBJECT_NAME: replaystream-ms
      WDM_CONSUMER_GRP_ID: sdr-replaystream-cg
      WDM_CLUSTER_CONTAINER_NAMES: '["replaystream-ms"]'
      VST_STREAMS_ENDPOINT: http://localhost:30000/api/v1/live/streams
      VST_STATUS_ENDPOINT: http://localhost:30000/api/v1/sensor/status
      OTEL_SDK_DISABLED: true
      WDM_INITIALIZE_FROM_VST: false
      ENVOY_REQUEST_TIMEOUT: 30
      WDM_TARGET_PORT_MAPPING: "{\"replaystream-ms-1\": ${REPLAYSTREAM_HTTP_PORT_1}}" #Comment this to scale upto 2 replaystream-ms
      #WDM_TARGET_PORT_MAPPING: "{\"replaystream-ms-1\": ${REPLAYSTREAM_HTTP_PORT_1}, \"replaystream-ms-2\": ${REPLAYSTREAM_HTTP_PORT_2}}" #Uncomment this to scale upto 2 replaystream-ms
      OTEL_SERVICE_NAME: SDR_AGENT
      WDM_REDIS_CACHE_OBJECT: "replaystream-data"
      WDM_WL_NAME_IGNORE_REGEX: ""
    deploy:
      resources:
        limits:
          memory: 300M
      restart_policy:
        condition: always
    depends_on:
      replaystream-ms-1-smc:
        condition: service_started
      # replaystream-ms-2: #Uncomment this to scale upto 2 replaystream-ms
      #   condition: service_started

  envoy-http-replaystream-smc:
    image: ${ENVOY_PROXY_IMAGE}
    profiles: ["bp_smc_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    user: "0:0"
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --concurrency 16 --base-id ${REPLAYSTREAM_BASE_ID}
    network_mode: "host"
    container_name: envoy-http-replaystream-smc
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      WDM_WL_REDIS_SERVER: ${REDIS_HOSTADDR}
      WDM_WL_REDIS_PORT: ${REDIS_PORT}
      WDM_KFK_BOOTSTRAP_URL: ${KAFKA_BOOTSTRAP_URL}
      WDM_WL_OBJECT_NAME: replaystream-ms
      ENVOYROUTEHEADER: "streamid"
      NOHEADERTARGETCONTAINER: "replaystream-01"
    depends_on:
      replaystream-ms-1-smc:
        condition: service_started
      # replaystream-ms-2: #Uncomment this to scale upto 2 replaystream-ms
      #   condition: service_started