
# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

global:
  ngcImagePullSecretName: ngc-docker-reg-secret

vss:
  nodeSelector:
    kubernetes.io/hostname: dgx-b200-08
  namespace: vss
  storageClassName: gpfs
  applicationSpecs:
    vss-deployment:
      containers:
        vss:
          image:
            pullPolicy: IfNotPresent
            repository: harbor.pyler.local/apps/dev/vss-engine
            tag: IMAGE_TAG
          env:
          - name: VLM_MODEL_TO_USE
            valueFrom:
              configMapKeyRef:
                name: vss-vlm-config
                key: VLM_MODEL_TO_USE
          - name: MODEL_PATH
            valueFrom:
              configMapKeyRef:
                name: vss-vlm-config
                key: MODEL_PATH
          # - name: VIA_VLM_OPENAI_MODEL_DEPLOYMENT_NAME
          #   valueFrom:
          #     configMapKeyRef:
          #       name: vss-vlm-config
          #       key: VIA_VLM_OPENAI_MODEL_DEPLOYMENT_NAME
          # - name: VIA_VLM_ENDPOINT
          #   valueFrom:
          #     configMapKeyRef:
          #       name: vss-vlm-config
          #       key: VIA_VLM_ENDPOINT
          - name: ENABLE_AUDIO
            value: 'true'
          - name: ENABLE_RIVA_SERVER_READINESS_CHECK
            value: 'true'
          # multi-language support
          - name: RIVA_ASR_SERVER_URI
            value: riva-multilang-service
          startupProbe:
            failureThreshold: 360

  configs:
    ca_rag_config.yaml:
      tools:
        chat_llm:
          params:
            base_url: http://llm-nim-svc:8000/v1
        notification_llm:
          params:
            base_url: http://llm-nim-svc:8000/v1
        nvidia_embedding:
          params:
            base_url: http://nemo-embedding-embedding-deployment-embedding-service:8000/v1
        nvidia_reranker:
          params:
            base_url: http://nemo-rerank-ranking-deployment-ranking-service:8000/v1
        summarization_llm:
          params:
            base_url: http://llm-nim-svc:8000/v1
    guardrails_config.yaml:
      models:
      - engine: nim
        model: meta/llama-3.1-70b-instruct
        parameters:
          base_url: http://llm-nim-svc:8000/v1
        type: main
      - engine: nim
        model: nvidia/llama-3.2-nv-embedqa-1b-v2
        parameters:
          base_url: http://nemo-embedding-embedding-deployment-embedding-service:8000/v1
        type: embeddings
  egress:
    # multi-language support
    riva-api:
      address: riva-multilang-service
      port: 9000
  resources:
    limits:
      nvidia.com/gpu: 2
  workloadSpecs:
    wl-env:
      wl_env:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            key: OPENAI_API_KEY
            name: infisical-managed-secrets
            optional: true
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NVIDIA_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: GRAPH_DB_USERNAME
        valueFrom:
          secretKeyRef:
            key: GRAPHDB_USER
            name: infisical-managed-secrets
      - name: GRAPH_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: GRAPHDB_PASSWORD
            name: infisical-managed-secrets
      - name: MINIO_USERNAME
        valueFrom:
          secretKeyRef:
            key: MINIO_USERNAME
            name: infisical-managed-secrets
      - name: MINIO_PASSWORD
        valueFrom:
          secretKeyRef:
            key: MINIO_PASSWORD
            name: infisical-managed-secrets
      - name: ARANGO_DB_USERNAME
        valueFrom:
          secretKeyRef:
            key: ARANGO_DB_USERNAME
            name: infisical-managed-secrets
      - name: ARANGO_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: ARANGO_DB_PASSWORD
            name: infisical-managed-secrets



etcd:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss
  storageClassName: gpfs

minio:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs
  applicationSpecs:
    minio-deployment:
      containers:
        minio-container:
          env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                key: MINIO_USERNAME
                name: infisical-managed-secrets
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MINIO_PASSWORD
                name: infisical-managed-secrets
  extraPodVolumes:
  - name: secret-access-key-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: MINIO_USERNAME
        path: access-key
  - name: secret-secret-key-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: MINIO_PASSWORD
        path: secret-key
  extraPodVolumeMounts:
  - name: secret-access-key-volume
    mountPath: /secrets/access-key
    subPath: access-key
    readOnly: true
  - name: secret-secret-key-volume
    mountPath: /secrets/secret-key
    subPath: secret-key
    readOnly: true

milvus:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs

neo4j:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs

  extraPodVolumes:
  - name: secret-db-username-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: GRAPHDB_USER
        path: db-username
  - name: secret-db-password-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: GRAPHDB_PASSWORD
        path: db-password
  extraPodVolumeMounts:
  - name: secret-db-username-volume
    mountPath: /secrets/db-username
    subPath: db-username
    readOnly: true
  - name: secret-db-password-volume
    mountPath: /secrets/db-password
    subPath: db-password
    readOnly: true

nim-llm:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss 
  storageClassName: gpfs
  persistence:
    storageClass: gpfs
  image:
    repository: nvcr.io/nim/meta/llama-3.1-70b-instruct
    tag: 1.10.1
  model:
    name: meta/llama-3.1-70b-instruct
    ngcAPISecret: infisical-managed-secrets
    tag: 1.10.1
  resources:
    limits:
      nvidia.com/gpu: 4


nemo-embedding:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs

  workloadSpecs:
    wl-env:
      wl_env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NIM_TRT_ENGINE_HOST_CODE_ALLOWED
        value: '1'
      - name: NIM_CACHE_PATH
        value: /mnt/nim-cache
      wl_units: 1
  resources:
    limits:
      nvidia.com/gpu: 1

nemo-rerank:
  namespace: vss  
  nodeSelector: 
    pyler.io/group: dgx
  storageClassName: gpfs
  workloadSpecs:
    wl-env:
      wl_env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NIM_CACHE_PATH
        value: /mnt/nim-cache
      wl_units: 1
  resources:
    limits:
      nvidia.com/gpu: 1

riva:
  enabled: true
  namespace: vss  
  nodeSelector: 
    pyler.io/group: dgx
  storageClassName: gpfs
  workloadSpecs:
    dummy: {}
    wl-env:
      wl_env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NIM_HTTP_API_PORT
        value: '9000'
      - name: NIM_GRPC_API_PORT
        value: '50051'
      - name: NIM_CACHE_PATH
        value: /mnt/nim-cache
      wl_units: 1

arango-db:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs
  applicationSpecs:
    arango-db-deployment:
      containers:
        arango-db-container:
          env:
          - name: ARANGO_DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: ARANGO_DB_USERNAME
                name: infisical-managed-secrets
          - name: ARANGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ARANGO_DB_PASSWORD
                name: infisical-managed-secrets
  extraPodVolumes:
  - name: secret-db-username-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: ARANGO_DB_USERNAME
        path: db-username
  - name: secret-db-password-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: ARANGO_DB_PASSWORD
        path: db-password
  extraPodVolumeMounts:
  - name: secret-db-username-volume
    mountPath: /secrets/db-username
    subPath: db-username
    readOnly: true
  - name: secret-db-password-volume
    mountPath: /secrets/db-password
    subPath: db-password
    readOnly: true
