global:
  ngcImagePullSecretName: ngc-docker-reg-secret

vss:
  nodeSelector: 
    kubernetes.io/hostname: dgx-b200-08
  namespace: vss
  storageClassName: gpfs
  # securityContext: {}
  # podSecurityContext: {}
  applicationSpecs:
    vss-deployment:
      securityContext:
        # fsGroup: 0
        runAsGroup: 0
        runAsUser: 0     
      containers:
        vss:
          image:
            pullPolicy: IfNotPresent
            repository: harbor.pyler.local/apps/dev/vss-engine
            tag: IMAGE_TAG
          env:
          - name: VLM_MODEL_TO_USE
            value: "openai-compat"
          - name: OPENAI_API_KEY
            value: "fake_key"
          - name: VIA_VLM_OPENAI_MODEL_DEPLOYMENT_NAME
            value: "VILA1.5-40B"
          - name: VIA_VLM_ENDPOINT
            value: "http://vila-server-service:8000/v1"
          # - name: MODEL_PATH
          #   value: ngc:nim/nvidia/vila-1.5-40b:vila-yi-34b-siglip-stage3_1003_video_v8
          - name: ENABLE_AUDIO
            value: 'true'
          - name: ENABLE_RIVA_SERVER_READINESS_CHECK
            value: 'true'
          # CV Pipeline
          # - name: INSTALL_PROPRIETARY_CODECS
          #   value: "true"
          # - name: DISABLE_CV_PIPELINE
          #   value: "false"
          # - name: GDINO_INFERENCE_INTERVAL
          #   value: "1"
          # - name: NUM_CV_CHUNKS_PER_GPU
          #   value: "2"
          # - name: VSS_LOG_LEVEL
          #   value: "DEBUG"
          startupProbe:
            failureThreshold: 360
  configs:
    ca_rag_config.yaml:
      chat:
        embedding:
          base_url: http://nemo-embedding-embedding-deployment-embedding-service:8000/v1
        llm:
          base_url: http://llm-nim-svc:8000/v1
          model: meta/llama-3.1-70b-instruct
        reranker:
          base_url: http://nemo-rerank-ranking-deployment-ranking-service:8000/v1
      notification:
        llm:
          base_url: http://llm-nim-svc:8000/v1
          model: meta/llama-3.1-70b-instruct
      summarization:
        embedding:
          base_url: http://nemo-embedding-embedding-deployment-embedding-service:8000/v1
        llm:
          base_url: http://llm-nim-svc:8000/v1
          model: meta/llama-3.1-70b-instruct
    guardrails_config.yaml:
      models:
      - engine: nim
        model: meta/llama-3.1-70b-instruct
        parameters:
          base_url: http://llm-nim-svc:8000/v1
        type: main
      - engine: nim
        model: nvidia/llama-3.2-nv-embedqa-1b-v2
        parameters:
          base_url: http://nemo-embedding-embedding-deployment-embedding-service:8000/v1
        type: embeddings
  # USE EXTERNAL VLM - GPU 리소스 할당 비활성화
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1
  # 기존 GPU 할당 주석 처리
  # resources:
  #   limits:
  #     nvidia.com/gpu: 2
  #     nvidia.com/gpu: 3 # CV Pipeline
  workloadSpecs:
    dummy: {}
    wl-env:
      wl_env:
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: infisical-managed-secrets
        - name: NVIDIA_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: infisical-managed-secrets
        - name: GRAPH_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: GRAPHDB_USER
              name: infisical-managed-secrets
        - name: GRAPH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GRAPHDB_PASSWORD
              name: infisical-managed-secrets
      wl_units: 1

etcd:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss
  storageClassName: gpfs

minio:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs


milvus:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs

neo4j:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs

  extraPodVolumes:
  - name: secret-db-username-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: GRAPHDB_USER
        path: db-username
  - name: secret-db-password-volume
    secret:
      secretName: infisical-managed-secrets
      items:
      - key: GRAPHDB_PASSWORD
        path: db-password
  extraPodVolumeMounts:
  - name: secret-db-username-volume
    mountPath: /secrets/db-username
    subPath: db-username
    readOnly: true
  - name: secret-db-password-volume
    mountPath: /secrets/db-password
    subPath: db-password
    readOnly: true


nim-llm:
  # CV Pipeline
  # env:
  # - name: NIM_MAX_MODEL_LEN
  #   value: "128000"
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss 
  storageClassName: gpfs
  persistence:
    storageClass: gpfs
  image:
    repository: nvcr.io/nim/meta/llama-3.1-70b-instruct
    tag: 1.10.1
  model:
    name: meta/llama-3.1-70b-instruct
    ngcAPISecret: infisical-managed-secrets
  resources:
    limits:
      nvidia.com/gpu: 4


nemo-embedding:
  nodeSelector: 
    pyler.io/group: dgx
  namespace: vss  
  storageClassName: gpfs
  workloadSpecs:
    wl-env:
      wl_env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NIM_TRT_ENGINE_HOST_CODE_ALLOWED
        value: '1'
      - name: NIM_CACHE_PATH
        value: /mnt/nim-cache
      wl_units: 1
  resources:
    limits:
      nvidia.com/gpu: 1

nemo-rerank:
  namespace: vss  
  nodeSelector: 
    pyler.io/group: dgx
  storageClassName: gpfs
  workloadSpecs:
    wl-env:
      wl_env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NIM_CACHE_PATH
        value: /mnt/nim-cache
      wl_units: 1
  resources:
    limits:
      nvidia.com/gpu: 1

riva:
  enabled: true
  namespace: vss  
  nodeSelector: 
    pyler.io/group: dgx
  storageClassName: gpfs
  workloadSpecs:
    dummy: {}
    wl-env:
      wl_env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NIM_HTTP_API_PORT
        value: '9000'
      - name: NIM_GRPC_API_PORT
        value: '50051'
      - name: NIM_CACHE_PATH
        value: /mnt/nim-cache
      wl_units: 1