riva:
  enabled: true
  namespace: vss  
  nodeSelector: 
    pyler.io/group: dgx
  storageClassName: gpfs
  applicationSpecs:
    riva-deployment:
      containers:
        riva-container:
          env:
          - name: NIM_TAGS_SELECTOR
            # value: name=parakeet-0-6b-ctc-riva-en-us,mode=all
            value: mode=all
          image:
            repository: nvcr.io/nim/nvidia/parakeet-1-1b-rnnt-multilingual
            tag: 1
      services:
        riva-multi-service:
          fullNameOverride: true
          ports:
          - name: http-api
            port: 9000
            targetPort: 9000
          - name: grpc-api
            port: 50051
            targetPort: 50051
      volumes:
      - name: riva-cache
        persistentVolumeClaim:
          claimName: riva-multi-nim-cache-pvc
  workloadSpecs:
    dummy: {}
    wl-env:
      wl_env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: infisical-managed-secrets
      - name: NIM_HTTP_API_PORT
        value: '9000'
      - name: NIM_GRPC_API_PORT
        value: '50051'
      - name: NIM_CACHE_PATH
        value: /mnt/nim-cache

      - name: DISABLE_RIVA_HTTP_SERVER
        value: "False"
      # gRPC(50051) 쓰려면
      - name: NIM_DISABLE_GRPC_STARTUP
        value: "False"
      # 내부 Triton을 같이 써야 모델 서빙이 정상 동작
      - name: NIM_DISABLE_TRITON_STARTUP
        value: "False"
      wl_units: 1