global:
  ngcImagePullSecretName: ngc-docker-reg-secret
namespace: vss  
nodeSelector: 
  pyler.io/group: dgx
storageClassName: gpfs
applicationSpecs:
  riva-deployment:
    containers:
      riva-container:
        env:
        - name: NIM_TAGS_SELECTOR
          # https://docs.nvidia.com/nim/speech/latest/asr/deploy-asr-models/parakeet-rnnt.html
          value: "mode=all" 
        image:
          repository: nvcr.io/nim/nvidia/parakeet-1-1b-rnnt-multilingual
          tag: latest
        livenessProbe:
          httpGet:
            path: /v1/health/live
            port: http-api
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /v1/health/ready
            port: http-api
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
        startupProbe:
          httpGet:
            path: /v1/health/ready
            port: http-api
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 480
    volumes:
    - name: riva-cache
      persistentVolumeClaim:
        claimName: riva-nim-cache-pvc
workloadSpecs:
  wl-env:
    wl_env:
    - name: NGC_API_KEY
      valueFrom:
        secretKeyRef:
          key: NGC_API_KEY
          name: infisical-managed-secrets
    - name: NIM_HTTP_API_PORT
      value: '9000'
    - name: NIM_GRPC_API_PORT
      value: '50051'
    - name: NIM_CACHE_PATH
      value: /mnt/nim-cache

    # - name: DISABLE_RIVA_HTTP_SERVER
    #   value: "False"
    # # gRPC(50051) 쓰려면
    # - name: NIM_DISABLE_GRPC_STARTUP
    #   value: "False"
    # # 내부 Triton을 같이 써야 모델 서빙이 정상 동작
    # - name: NIM_DISABLE_TRITON_STARTUP
    #   value: "False"
    wl_units: 1
