apiVersion: v1
kind: Service
metadata:
  namespace: vss
  name: vila-server-service
spec:
  selector:
    app: vila-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP