name: VSS Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: sel2-arc-runners
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set Environments
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "PROJECT_ENV=prod" >> $GITHUB_ENV
          else
            echo "PROJECT_ENV=dev" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to NGC
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: '$oauthtoken'
          password: ${{ secrets.NGC_API_KEY }}
          

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build & Push VSS Engine Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/vss-engine
          push: true
          tags: ${{ vars.HARBOR_REGISTRY }}/apps/${{ env.PROJECT_ENV }}/vss-engine:${{ github.sha }}
          file: ./src/vss-engine/docker/Dockerfile
          build-args: |
            BASE_IMAGE=nvcr.io/nvidia/blueprint/vss-engine-base:2.3.1
