apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vss-ngc-model-cache-cv-pipeline
  namespace: vss
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gpfs
  volumeMode: Filesystem