services:
  rtspserver-ms-1-3d:
    image: ${VST_RTSPSERVER_IMAGE}
    profiles: ["bp_wh_kafka_3d","bp_wh_redis_3d"]
    container_name: rtspserver-ms-1-3d
    network_mode: host
    runtime: nvidia
    user: "0:0"
    entrypoint: ["/bin/bash", "-c", "exec /home/vst/vst_release/launch_vst"]
    environment:
      - VST_INSTALL_ADDITIONAL_PACKAGES=${VST_INSTALL_ADDITIONAL_PACKAGES}
      - ADAPTOR=rtsp-ms
      - HTTP_PORT=${RTSP_SERVER_HTTP_PORT_1}
      - RTSP_SERVER_PORT=${RTSP_SERVER_PORT_1}
      - CENTRALIZE_DB_NAME=${CENTRALIZE_DB_NAME}
      - CENTRALIZE_DB_USERNAME=${CENTRALIZE_DB_USERNAME}
      - STORAGE_MODULE_ENDPOINT=${STORAGE_MODULE_ENDPOINT}
      - SENSOR_MODULE_ENDPOINT=${SENSOR_MODULE_ENDPOINT}
    volumes:
      - ${VST_CONFIG_PATH}:/home/vst/vst_release/configs
      - ${VST_CONFIG_PATH}/vst_config_${STREAM_TYPE:-redis}.json:/home/vst/vst_release/configs/vst_config.json
      - ${VST_DATA_PATH}:/home/vst/vst_release/vst_data
      - ${VST_VIDEO_STORAGE_PATH}:/home/vst/vst_release/vst_video
      - ${MDX_SAMPLE_APPS_DIR}/vst/scripts/user_additional_install.sh:/home/vst/vst_release/tools/user_additional_install.sh
    deploy:
      restart_policy:
        condition: always
    depends_on:
      centralizedb-3d:
        condition: service_started
      vst-ingress-3d:
        condition: service_started
      sdr-http-recorder-3d:
        condition: service_started
      envoy-http-recorder-3d:
        condition: service_started

  sdr-http-rtspserver-3d:
    image: ${SDR_IMAGE}
    profiles: ["bp_wh_kafka_3d","bp_wh_redis_3d"]
    user: "0:0"
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "8192m"
        max-file: "3"
    container_name: sdr-http-rtspserver-3d
    volumes:
      - ./sdr-config:/wdm-configs
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VST_DATA_PATH}/sdr/rtspserver/log:/log
    environment:
      PORT: 4003
      WDM_CLUSTER_CONFIG_FILE: /wdm-configs/docker_cluster_config.json
      WDM_MSG_KEY: ${REDIS_MSG_KEY}
      WDM_WL_REDIS_SERVER: ${REDIS_HOSTADDR}
      WDM_WL_REDIS_PORT: ${REDIS_PORT}
      WDM_WL_REDIS_MSG_FIELD: sensor.id
      WDM_WL_ADD_URL: /api/v1/proxy/stream/add
      WDM_WL_DELETE_URL: /api/v1/proxy/stream/
      WDM_WL_HEALTH_CHECK_URL: /api/v1/proxy/configuration
      WDM_WL_CHANGE_ID_ADD: camera_proxy
      WDM_WL_CHANGE_ID_DEL: camera_remove
      WDM_PRELOAD_WORKLOAD: ./tests/event_pre-roll.json
      WDM_CLEAR_DATA_WL: true
      WDM_KFK_ENABLE: false
      WDM_MSG_TOPIC: vst_events
      WDM_KFK_BOOTSTRAP_URL: ${KAFKA_BOOTSTRAP_URL}
      WDM_DS_SWAP_ID_NAME: false
      WDM_WL_THRESHOLD: 100
      WDM_ADD_REMOVE_RETRY_ATTEMPTS: 50
      WDM_CLUSTER_TYPE: docker
      WDM_POD_WATCH_DOCKER_DELAY: 0.5
      WDM_RESTART_DS_ON_ADD_FAIL: false
      WDM_DISABLE_WERKZEUG_LOGGING: true
      WDM_WL_OBJECT_NAME: rtspserver-ms
      WDM_CONSUMER_GRP_ID: sdr-rtspserver-cg
      WDM_CLUSTER_CONTAINER_NAMES: '["rtspserver-ms"]'
      VST_STREAMS_ENDPOINT: http://localhost:30000/api/v1/live/streams
      VST_STATUS_ENDPOINT: http://localhost:30000/api/v1/sensor/status
      OTEL_SDK_DISABLED: true
      WDM_INITIALIZE_FROM_VST: false
      ENVOY_REQUEST_TIMEOUT: 30
      WDM_TARGET_PORT_MAPPING: "{\"rtspserver-ms-1\": ${RTSP_SERVER_HTTP_PORT_1}}"
      OTEL_SERVICE_NAME: SDR_AGENT
      WDM_REDIS_CACHE_OBJECT: "rtspserver-data"
    deploy:
      resources:
        limits:
          memory: 300M
      restart_policy:
        condition: always
    depends_on:
      rtspserver-ms-1-3d:
        condition: service_started
        
  envoy-http-rtspserver-3d:
    image: ${ENVOY_PROXY_IMAGE}
    profiles: ["bp_wh_kafka_3d","bp_wh_redis_3d"]
    user: "0:0"
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --concurrency 16 --base-id ${RTSPSERVER_BASE_ID}
    network_mode: "host"
    container_name: envoy-http-rtspserver-3d
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      WDM_WL_REDIS_SERVER: ${REDIS_HOSTADDR}
      WDM_WL_REDIS_PORT: ${REDIS_PORT}
      WDM_KFK_BOOTSTRAP_URL: ${KAFKA_BOOTSTRAP_URL}
      WDM_WL_OBJECT_NAME: rtspserver-ms
      ENVOYROUTEHEADER: "streamid"
      NOHEADERTARGETCONTAINER: "rtspserver-01"
    depends_on:
      rtspserver-ms-1-3d:
        condition: service_started